Add all-passed job
Too many status checks to check for branch protection rule.
This consolidates everything to one job that checks for us.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -118,3 +118,20 @@ jobs:
         with:
           user: __token__
           password: ${{ secrets.pypi_password }}
+
+  all-passed:
+    runs-on: ubuntu-latest
+    needs:
+      - pre-commit
+      - tests
+      - docs
+      - dist
+    if: always()
+    steps:
+      - name: Fail if any dependency did not succeed
+        run: |
+          echo "Upstream results: ${{ join(needs.*.result, ', ') }}"
+          # If any result is failure/cancelled/skipped, fail this job
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}" == "true" ]]; then
+            exit 1
+          fi
